apiVersion: v1
kind: Namespace
metadata:
  name: kubesphere-system
spec: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
  namespace: kubesphere-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
data:
  bootstrap.ldif: |
    dn: ou=Users,dc=kubesphere,dc=io
    objectClass: organizationalUnit
    objectClass: top
    ou: Users

    dn: ou=Groups,dc=kubesphere,dc=io
    objectClass: organizationalUnit
    objectClass: top
    ou: Users
    ou: Groups

    dn: uid=admin,ou=Users,dc=kubesphere,dc=io
    objectClass: inetOrgPerson
    objectClass: top
    cn: admin
    sn: admin
    uid: admin
    userPassword:: e1NTSEF9YTlZZVBhT3cvRE8wTWN0L2YwRDhHcDRISllZM0VWam8K

    dn: uid=mohamed,ou=Users,dc=kubesphere,dc=io
    objectClass: inetOrgPerson
    objectClass: top
    cn: Mohamed
    sn: User
    uid: mohamed
    userPassword:: e1NTSEF9YTlZZVBhT3cvRE8wTWN0L2YwRDhHcDRISllZM0VWam8K

kind: ConfigMap
metadata:
  name: openldap-bootstrap
  namespace: kubesphere-system

---

apiVersion: v1
kind: Pod
metadata:
  name: openldap-0
  labels:
    app.kubernetes.io/instance: ks-openldap
    app.kubernetes.io/name: openldap-ha
  namespace: kubesphere-system
spec:
  containers:
  - args:
    - --copy-service
    - --loglevel=warning
    env:
    - name: LDAP_ORGANISATION
      value: kubesphere
    - name: LDAP_DOMAIN
      value: kubesphere.io
    - name: LDAP_CONFIG_PASSWORD
      value: admin
    - name: LDAP_ADMIN_PASSWORD
      value: admin
    - name: LDAP_REPLICATION
      value: "false"
    - name: LDAP_TLS
      value: "false"
    - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
      value: "true"
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: HOSTNAME
      value: $(MY_POD_NAME).openldap
    image: osixia/openldap:1.3.0

    name: openldap-ha
    ports:
    - containerPort: 389
      name: ldap
      protocol: TCP

    volumeMounts:
    - mountPath: /var/lib/ldap
      name: openldap-pvc
      subPath: ldap-data
    - mountPath: /etc/ldap/slapd.d
      name: openldap-pvc
      subPath: ldap-config
    - mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
      name: openldap-bootstrap
  volumes:
  - name: openldap-pvc
    persistentVolumeClaim:
      claimName: openldap-pvc
  - configMap:
      defaultMode: 420
      name: openldap-bootstrap
    name: openldap-bootstrap

---

apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: kubesphere-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ldap
    port: 389
    protocol: TCP
    targetPort: 389
  selector:
    app.kubernetes.io/instance: ks-openldap
    app.kubernetes.io/name: openldap-ha
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---