name: Helm Chart Releaser

on: 
  workflow_dispatch:
  push:
    paths:
      - charts/**
      - .github/workflows/*
    tags:
      - 'v*.*.*'
    branches:
      - 'release-*.*'
      - 'release-*.*.*'
      - 'main'

jobs:
  chart-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"